/*
 * Port_config.h
 *
 *  Created on: Apr 20, 2020
 *      Author: dimagic
 */

#ifndef ROBOCUP_TIMER_INC_PORT_CONFIG_H_
#define ROBOCUP_TIMER_INC_PORT_CONFIG_H_

#include "variation.h"

/* MOTOR PWM Channel assigment*/
#define PWM_1A_TIM 			TIM3
#define PWM_1A_TIM_CHANNEL 	TIM_CHANNEL_1
#define PWM_1A_GPIO 		GPIOB
#define PWM_1A_GPIO_PIN 	GPIO_PIN_4
#define PWM_1A_GPIO_AF 		GPIO_AF2_TIM3
#define PWM_1B_TIM 			TIM3
#define PWM_1B_TIM_CHANNEL 	TIM_CHANNEL_2
#define PWM_1B_GPIO 		GPIOB
#define PWM_1B_GPIO_PIN 	GPIO_PIN_5
#define PWM_1B_GPIO_AF 		GPIO_AF2_TIM3

#define PWM_2A_TIM 			TIM5
#define PWM_2A_TIM_CHANNEL 	TIM_CHANNEL_1
#define PWM_2A_GPIO 		GPIOA
#define PWM_2A_GPIO_PIN 	GPIO_PIN_0
#define PWM_2A_GPIO_AF 		GPIO_AF2_TIM5
#define PWM_2B_TIM 			TIM5
#define PWM_2B_TIM_CHANNEL 	TIM_CHANNEL_2
#define PWM_2B_GPIO 		GPIOA
#define PWM_2B_GPIO_PIN 	GPIO_PIN_1
#define PWM_2B_GPIO_AF 		GPIO_AF2_TIM5

#define PWM_3A_TIM 			TIM3
#define PWM_3A_TIM_CHANNEL 	TIM_CHANNEL_3
#define PWM_3A_GPIO 		GPIOB
#define PWM_3A_GPIO_PIN 	GPIO_PIN_0
#define PWM_3A_GPIO_AF 		GPIO_AF1_TIM3
#define PWM_3B_TIM 			TIM3
#define PWM_3B_TIM_CHANNEL 	TIM_CHANNEL_4
#define PWM_3B_GPIO 		GPIOB
#define PWM_3B_GPIO_PIN 	GPIO_PIN_1
#define PWM_3B_GPIO_AF 		GPIO_AF1_TIM3

#define PWM_4A_TIM 			TIM15
#define PWM_4A_TIM_CHANNEL 	TIM_CHANNEL_1
#define PWM_4A_GPIO 		GPIOB
#define PWM_4A_GPIO_PIN 	GPIO_PIN_14
#define PWM_4A_GPIO_AF 		GPIO_AF2_TIM15
#define PWM_4B_TIM 			TIM15
#define PWM_4B_TIM_CHANNEL 	TIM_CHANNEL_2
#define PWM_4B_GPIO 		GPIOB
#define PWM_4B_GPIO_PIN 	GPIO_PIN_15
#define PWM_4B_GPIO_AF 		GPIO_AF2_TIM15

/* MOTOR encoder Channel assigment*/
#define ENC_1A_TIM 			TIM1
#define ENC_1A_TIM_CHANNEL 	TIM_CHANNEL_1
#define ENC_1A_GPIO 		GPIOA
#define ENC_1A_GPIO_PIN 	GPIO_PIN_8
#define ENC_1A_GPIO_AF 		GPIO_AF1_TIM1
#define ENC_1B_TIM 			TIM1
#define ENC_1B_TIM_CHANNEL 	TIM_CHANNEL_2
#define ENC_1B_GPIO 		GPIOA
#define ENC_1B_GPIO_PIN 	GPIO_PIN_9
#define ENC_1B_GPIO_AF 		GPIO_AF1_TIM1
#define ENC_1_TIM_CNT		ENC_1A_TIM->CNT
#define ENC_1_TIM_DIR		(ENC_1A_TIM->CR1 & TIM_CR1_DIR)


#define ENC_2A_TIM 			TIM2
#define ENC_2A_TIM_CHANNEL 	TIM_CHANNEL_1
#define ENC_2A_GPIO 		GPIOA
#define ENC_2A_GPIO_PIN 	GPIO_PIN_5
#define ENC_2A_GPIO_AF 		GPIO_AF1_TIM2
#define ENC_2B_TIM 			TIM2
#define ENC_2B_TIM_CHANNEL 	TIM_CHANNEL_2
#define ENC_2B_GPIO 		GPIOB
#define ENC_2B_GPIO_PIN 	GPIO_PIN_3
#define ENC_2B_GPIO_AF 		GPIO_AF1_TIM2
#define ENC_2_TIM_CNT		ENC_2A_TIM->CNT
#define ENC_2_TIM_DIR		(ENC_2A_TIM->CR1 & TIM_CR1_DIR)

#define ENC_3A_TIM 			TIM4
#define ENC_3A_TIM_CHANNEL 	TIM_CHANNEL_1
#define ENC_3A_GPIO 		GPIOB
#define ENC_3A_GPIO_PIN 	GPIO_PIN_6
#define ENC_3A_GPIO_AF 		GPIO_AF1_TIM4
#define ENC_3B_TIM 			TIM4
#define ENC_3B_TIM_CHANNEL 	TIM_CHANNEL_2
#define ENC_3B_GPIO 		GPIOB
#define ENC_3B_GPIO_PIN 	GPIO_PIN_7
#define ENC_3B_GPIO_AF 		GPIO_AF1_TIM4
#define ENC_3_TIM_CNT		ENC_3A_TIM->CNT
#define ENC_3_TIM_DIR		(ENC_3A_TIM->CR1 & TIM_CR1_DIR)

#define ENC_4A_TIM 			TIM8
#define ENC_4A_TIM_CHANNEL 	TIM_CHANNEL_1
#define ENC_4A_GPIO 		GPIOC
#define ENC_4A_GPIO_PIN 	GPIO_PIN_6
#define ENC_4A_GPIO_AF 		GPIO_AF2_TIM8
#define ENC_4B_TIM 			TIM8
#define ENC_4B_TIM_CHANNEL 	TIM_CHANNEL_2
#define ENC_4B_GPIO 		GPIOC
#define ENC_4B_GPIO_PIN 	GPIO_PIN_7
#define ENC_4B_GPIO_AF 		GPIO_AF2_TIM8
#define ENC_4_TIM_CNT		ENC_4A_TIM->CNT
#define ENC_4_TIM_DIR		(ENC_4A_TIM->CR1 & TIM_CR1_DIR)

#ifdef HUMAN_CONTROLLED
#define IC_IN_USE				3u

#define IC_1_TIM				TIM1
#define IC_1_TIM_CHANNEL 		TIM_CHANNEL_4
#define IC_1_GPIO 				GPIOA
#define IC_1_GPIO_PIN 			GPIO_PIN_11
#define IC_1_GPIO_AF 			GPIO_AF1_TIM1
#define IC_1_IRQn	    		TIM1_CC_IRQn
#define IC_1_TIM_ACT_CHANNEL	HAL_TIM_ACTIVE_CHANNEL_4

#define IC_2_TIM				TIM8
#define IC_2_TIM_CHANNEL 		TIM_CHANNEL_3
#define IC_2_GPIO 				GPIOC
#define IC_2_GPIO_PIN 			GPIO_PIN_8
#define IC_2_GPIO_AF 			GPIO_AF1_TIM8
#define IC_2_IRQn	    		TIM8_CC_IRQn
#define IC_2_TIM_ACT_CHANNEL	HAL_TIM_ACTIVE_CHANNEL_3

#define IC_3_TIM				TIM8
#define IC_3_TIM_CHANNEL 		TIM_CHANNEL_4
#define IC_3_GPIO 				GPIOC
#define IC_3_GPIO_PIN 			GPIO_PIN_9
#define IC_3_GPIO_AF 			GPIO_AF1_TIM8
#define IC_3_IRQn	    		TIM8_CC_IRQn
#define IC_3_TIM_ACT_CHANNEL	HAL_TIM_ACTIVE_CHANNEL_4
#endif

#endif /* ROBOCUP_TIMER_INC_PORT_CONFIG_H_ */
