/*
 * Port_config.h
 *
 *  Created on: Apr 20, 2020
 *      Author: dimagic
 */

#ifndef ROBOCUP_TIMER_INC_PORT_CONFIG_H_
#define ROBOCUP_TIMER_INC_PORT_CONFIG_H_

#include "variation.h"

/* MOTOR PWM Channel assigment*/
#define PWM_1A_TIM 			TIM2
#define PWM_1A_TIM_CHANNEL 	TIM_CHANNEL_1
#define PWM_1A_GPIO 		GPIOA
#define PWM_1A_GPIO_PIN 	GPIO_PIN_0
#define PWM_1A_GPIO_AF 		GPIO_AF1_TIM2
#define PWM_1B_TIM 			TIM2
#define PWM_1B_TIM_CHANNEL 	TIM_CHANNEL_2
#define PWM_1B_GPIO 		GPIOA
#define PWM_1B_GPIO_PIN 	GPIO_PIN_1
#define PWM_1B_GPIO_AF 		GPIO_AF1_TIM2

#define PWM_2A_TIM 			TIM3
#define PWM_2A_TIM_CHANNEL 	TIM_CHANNEL_1
#define PWM_2A_GPIO 		GPIOB
#define PWM_2A_GPIO_PIN 	GPIO_PIN_4
#define PWM_2A_GPIO_AF 		GPIO_AF2_TIM3
#define PWM_2B_TIM 			TIM2
#define PWM_2B_TIM_CHANNEL 	TIM_CHANNEL_2
#define PWM_2B_GPIO 		GPIOB
#define PWM_2B_GPIO_PIN 	GPIO_PIN_5
#define PWM_2B_GPIO_AF 		GPIO_AF2_TIM3

#define PWM_3A_TIM 			TIM2
#define PWM_3A_TIM_CHANNEL 	TIM_CHANNEL_3
#define PWM_3A_GPIO 		GPIOB
#define PWM_3A_GPIO_PIN 	GPIO_PIN_10
#define PWM_3A_GPIO_AF 		GPIO_AF1_TIM2
#define PWM_3B_TIM 			TIM2
#define PWM_3B_TIM_CHANNEL 	TIM_CHANNEL_4
#define PWM_3B_GPIO 		GPIOB
#define PWM_3B_GPIO_PIN 	GPIO_PIN_11
#define PWM_3B_GPIO_AF 		GPIO_AF1_TIM2

#define PWM_4A_TIM 			TIM3
#define PWM_4A_TIM_CHANNEL 	TIM_CHANNEL_3
#define PWM_4A_GPIO 		GPIOB
#define PWM_4A_GPIO_PIN 	GPIO_PIN_0
#define PWM_4A_GPIO_AF 		GPIO_AF2_TIM3
#define PWM_4B_TIM 			TIM3
#define PWM_4B_TIM_CHANNEL 	TIM_CHANNEL_4
#define PWM_4B_GPIO 		GPIOC
#define PWM_4B_GPIO_PIN 	GPIO_PIN_9
#define PWM_4B_GPIO_AF 		GPIO_AF2_TIM3

/* MOTOR encoder Channel assigment*/
#define ENC_1A_TIM 			TIM2
#define ENC_1A_TIM_CHANNEL 	TIM_CHANNEL_1
#define ENC_1A_GPIO 		GPIOA
#define ENC_1A_GPIO_PIN 	GPIO_PIN_0
#define ENC_1A_GPIO_AF 		GPIO_AF1_TIM2
#define ENC_1B_TIM 			TIM2
#define ENC_1B_TIM_CHANNEL 	TIM_CHANNEL_2
#define ENC_1B_GPIO 		GPIOA
#define ENC_1B_GPIO_PIN 	GPIO_PIN_1
#define ENC_1B_GPIO_AF 		GPIO_AF1_TIM2

#define ENC_2A_TIM 			TIM3
#define ENC_2A_TIM_CHANNEL 	TIM_CHANNEL_1
#define ENC_2A_GPIO 		GPIOB
#define ENC_2A_GPIO_PIN 	GPIO_PIN_4
#define ENC_2A_GPIO_AF 		GPIO_AF2_TIM3
#define ENC_2B_TIM 			TIM2
#define ENC_2B_TIM_CHANNEL 	TIM_CHANNEL_2
#define ENC_2B_GPIO 		GPIOB
#define ENC_2B_GPIO_PIN 	GPIO_PIN_5
#define ENC_2B_GPIO_AF 		GPIO_AF2_TIM3

#define ENC_3A_TIM 			TIM2
#define ENC_3A_TIM_CHANNEL 	TIM_CHANNEL_3
#define ENC_3A_GPIO 		GPIOB
#define ENC_3A_GPIO_PIN 	GPIO_PIN_10
#define ENC_3A_GPIO_AF 		GPIO_AF1_TIM2
#define ENC_3B_TIM 			TIM2
#define ENC_3B_TIM_CHANNEL 	TIM_CHANNEL_4
#define ENC_3B_GPIO 		GPIOB
#define ENC_3B_GPIO_PIN 	GPIO_PIN_11
#define ENC_3B_GPIO_AF 		GPIO_AF1_TIM2

#define ENC_4A_TIM 			TIM3
#define ENC_4A_TIM_CHANNEL 	TIM_CHANNEL_3
#define ENC_4A_GPIO 		GPIOB
#define ENC_4A_GPIO_PIN 	GPIO_PIN_0
#define ENC_4A_GPIO_AF 		GPIO_AF2_TIM3
#define ENC_4B_TIM 			TIM3
#define ENC_4B_TIM_CHANNEL 	TIM_CHANNEL_4
#define ENC_4B_GPIO 		GPIOC
#define ENC_4B_GPIO_PIN 	GPIO_PIN_9
#define ENC_4B_GPIO_AF 		GPIO_AF2_TIM3

#ifdef HUMAN_CONTROLLED
#define IC_IN_USE				3u

#define IC_1_TIM				TIM1
#define IC_1_TIM_CHANNEL 		TIM_CHANNEL_1
#define IC_1_GPIO 				GPIOA
#define IC_1_GPIO_PIN 			GPIO_PIN_8
#define IC_1_GPIO_AF 			GPIO_AF1_TIM1
#define IC_1_IRQn	    		TIM1_CC_IRQn
#define IC_1_TIM_ACT_CHANNEL	HAL_TIM_ACTIVE_CHANNEL_1

#define IC_2_TIM				TIM1
#define IC_2_TIM_CHANNEL 		TIM_CHANNEL_2
#define IC_2_GPIO 				GPIOA
#define IC_2_GPIO_PIN 			GPIO_PIN_9
#define IC_2_GPIO_AF 			GPIO_AF1_TIM1
#define IC_2_IRQn	    		TIM1_CC_IRQn
#define IC_2_TIM_ACT_CHANNEL	HAL_TIM_ACTIVE_CHANNEL_2

#define IC_3_TIM				TIM1
#define IC_3_TIM_CHANNEL 		TIM_CHANNEL_4
#define IC_3_GPIO 				GPIOA
#define IC_3_GPIO_PIN 			GPIO_PIN_11
#define IC_3_GPIO_AF 			GPIO_AF1_TIM1
#define IC_3_IRQn	    		TIM1_CC_IRQn
#define IC_3_TIM_ACT_CHANNEL	HAL_TIM_ACTIVE_CHANNEL_4
#endif

#endif /* ROBOCUP_TIMER_INC_PORT_CONFIG_H_ */
